### ISSUE TITLE
Add interpolation type flag to -resize

### ISSUE THREAD

**Issue by DashDashDashDashDash** [Jacherr/assyst-tracking#27]
I figure it'd be helpful to add a flag that determines the type of filtering used for resizing images, since some images may produce better quality results in a different filtering option.
Doing a lazy search through [image-rs/image](https://github.com/image-rs/image/) (which i assume is the library used) has given me [five](https://github.com/image-rs/image/blob/master/src/imageops/sample.rs#L82-L97) different interpolation filters; surely the workload for additional resize commands won't be impactful enough to make a difference.

**Comment by Jacherr** [comment]
The one that's currently used was chosen because it's by far the fastest and least computationally intensive.

I could probably add Gaussian resizing as an alternative, but it will probably end up being a flag on the existing command that is disabled by default. The other methods don't offer a balance of quality to performance that I am comfortable implementing into the bot.

**Comment by y21** [comment]
You can now change the algorithm used for resizing images as suggested. Do keep in mind that flags were just added and are still very much experimental, so there might be bugs

The syntax for this still needs to be properly documented, but for now you can find it [here](https://github.com/Jacherr/assyst-tracking/issues/5#issuecomment-897142145). Example: `-resize <image> 600x600 -filter gaussian`
