### ISSUE TITLE
Suggestion: -badcommand

### ISSUE THREAD

**Issue by DemonTamer534** [Jacherr/assyst-tracking#28]
DT already suggested that in walking but i wanted to bring it up again cuz i really like the idea: -badcommand, which puts the image trough several random image commands and spits it back out

**Comment by y21** [comment]
We now have `-randomize`, which applies random filters on the input image as suggested. However, there are a few problems with it currently and I'll try to fix these before announcing this command:

- [ ] Some filters result in different file formats (GIF/PNG) and other filters only accept a specific file format. A workaround for this would be only accepting filters for the randomize command that accept both static images and GIFs as input
- [ ] Duplicate filters. It's possible for the same filter to be applied twice. Sometimes, this doesn't make sense. We could just add a flag for *allowing* duplicates, and disabling them by default
- [ ] Errors such as timeouts. Instead of completely rejecting the command and responding with an error, we might want to respond with the last image that we had before an error occurred.

**Comment by Diamondtroller** [comment]
Is there a reason you don't want to call it `-badcommand`?
I guess you could also make the commands output APNGs but that would need a lot of rewrites?

**Comment by Jacherr** [comment]
An alias for `-badcommand` could easily be added, I don't see a reason not to do this.

It's not reasonable to output APNGs instead of GIFs yet, because Discord doesn't support APNG rendering outside of stickers. This is a change I will gladly make once they do, since APNGs are faster to encode, support partial transparency, and usually have a smaller file size.

**Comment by y21** [comment]
> Is there a reason you don't want to call it `-badcommand`?

@Diamondtroller Yeah, I didn't use the name because it was really vague and it might be unclear what it is to someone reading the help page. But we can add this as an alias.

**Comment by y21** [comment]
Closing this because the [todo list](https://github.com/Jacherr/assyst-tracking/issues/28#issuecomment-905050642) for this command is complete
